app:
  preview:
    id: ${HEROKU_APP_NAME:local}
    is-review: ${HEROKU_REVIEW_APP:false}

spring:
  application:
    name: posting
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration

server:
  port: ${PORT:8081}

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /swagger-ui
  show-actuator: true
